/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppConnectRouteImport } from './routes/_authenticated/app.connect'
import { Route as AuthenticatedAppOfficeHoursRouteImport } from './routes/_authenticated/app.office-hours'
import { Route as AuthenticatedAppOpportunitiesRouteImport } from './routes/_authenticated/app.opportunities'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppReferralsRouteImport } from './routes/_authenticated/app.referrals'
import { Route as AuthenticatedAppResourcesRouteImport } from './routes/_authenticated/app.resources'
import { Route as AuthenticatedAppStoriesRouteImport } from './routes/_authenticated/app.stories'
import { Route as AuthenticatedAppForumIndexRouteImport } from './routes/_authenticated/app.forum.index'
import { Route as AuthenticatedAppForumIdRouteImport } from './routes/_authenticated/app.forum.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConnectRoute = AuthenticatedAppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOfficeHoursRoute =
  AuthenticatedAppOfficeHoursRouteImport.update({
    id: '/office-hours',
    path: '/office-hours',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpportunitiesRoute =
  AuthenticatedAppOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReferralsRoute =
  AuthenticatedAppReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppResourcesRoute =
  AuthenticatedAppResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStoriesRoute = AuthenticatedAppStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppForumIndexRoute =
  AuthenticatedAppForumIndexRouteImport.update({
    id: '/forum/',
    path: '/forum/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppForumIdRoute = AuthenticatedAppForumIdRouteImport.update({
  id: '/forum/$id',
  path: '/forum/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/connect': typeof AuthenticatedAppConnectRoute
  '/app/office-hours': typeof AuthenticatedAppOfficeHoursRoute
  '/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/resources': typeof AuthenticatedAppResourcesRoute
  '/app/stories': typeof AuthenticatedAppStoriesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/forum/$id': typeof AuthenticatedAppForumIdRoute
  '/app/forum/': typeof AuthenticatedAppForumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/connect': typeof AuthenticatedAppConnectRoute
  '/app/office-hours': typeof AuthenticatedAppOfficeHoursRoute
  '/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/resources': typeof AuthenticatedAppResourcesRoute
  '/app/stories': typeof AuthenticatedAppStoriesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/forum/$id': typeof AuthenticatedAppForumIdRoute
  '/app/forum': typeof AuthenticatedAppForumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/connect': typeof AuthenticatedAppConnectRoute
  '/_authenticated/app/office-hours': typeof AuthenticatedAppOfficeHoursRoute
  '/_authenticated/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/_authenticated/app/resources': typeof AuthenticatedAppResourcesRoute
  '/_authenticated/app/stories': typeof AuthenticatedAppStoriesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/forum/$id': typeof AuthenticatedAppForumIdRoute
  '/_authenticated/app/forum/': typeof AuthenticatedAppForumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/chat'
    | '/app/connect'
    | '/app/office-hours'
    | '/app/opportunities'
    | '/app/profile'
    | '/app/referrals'
    | '/app/resources'
    | '/app/stories'
    | '/app/'
    | '/app/forum/$id'
    | '/app/forum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/chat'
    | '/app/connect'
    | '/app/office-hours'
    | '/app/opportunities'
    | '/app/profile'
    | '/app/referrals'
    | '/app/resources'
    | '/app/stories'
    | '/app'
    | '/app/forum/$id'
    | '/app/forum'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/connect'
    | '/_authenticated/app/office-hours'
    | '/_authenticated/app/opportunities'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/referrals'
    | '/_authenticated/app/resources'
    | '/_authenticated/app/stories'
    | '/_authenticated/app/'
    | '/_authenticated/app/forum/$id'
    | '/_authenticated/app/forum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/connect': {
      id: '/_authenticated/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AuthenticatedAppConnectRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/office-hours': {
      id: '/_authenticated/app/office-hours'
      path: '/office-hours'
      fullPath: '/app/office-hours'
      preLoaderRoute: typeof AuthenticatedAppOfficeHoursRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/opportunities': {
      id: '/_authenticated/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AuthenticatedAppOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/referrals': {
      id: '/_authenticated/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AuthenticatedAppReferralsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/resources': {
      id: '/_authenticated/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AuthenticatedAppResourcesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/stories': {
      id: '/_authenticated/app/stories'
      path: '/stories'
      fullPath: '/app/stories'
      preLoaderRoute: typeof AuthenticatedAppStoriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/forum/': {
      id: '/_authenticated/app/forum/'
      path: '/forum'
      fullPath: '/app/forum/'
      preLoaderRoute: typeof AuthenticatedAppForumIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/forum/$id': {
      id: '/_authenticated/app/forum/$id'
      path: '/forum/$id'
      fullPath: '/app/forum/$id'
      preLoaderRoute: typeof AuthenticatedAppForumIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppConnectRoute: typeof AuthenticatedAppConnectRoute
  AuthenticatedAppOfficeHoursRoute: typeof AuthenticatedAppOfficeHoursRoute
  AuthenticatedAppOpportunitiesRoute: typeof AuthenticatedAppOpportunitiesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReferralsRoute: typeof AuthenticatedAppReferralsRoute
  AuthenticatedAppResourcesRoute: typeof AuthenticatedAppResourcesRoute
  AuthenticatedAppStoriesRoute: typeof AuthenticatedAppStoriesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppForumIdRoute: typeof AuthenticatedAppForumIdRoute
  AuthenticatedAppForumIndexRoute: typeof AuthenticatedAppForumIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppConnectRoute: AuthenticatedAppConnectRoute,
  AuthenticatedAppOfficeHoursRoute: AuthenticatedAppOfficeHoursRoute,
  AuthenticatedAppOpportunitiesRoute: AuthenticatedAppOpportunitiesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReferralsRoute: AuthenticatedAppReferralsRoute,
  AuthenticatedAppResourcesRoute: AuthenticatedAppResourcesRoute,
  AuthenticatedAppStoriesRoute: AuthenticatedAppStoriesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppForumIdRoute: AuthenticatedAppForumIdRoute,
  AuthenticatedAppForumIndexRoute: AuthenticatedAppForumIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
